### ISSUE TITLE
4月14日起，因为百度不知道改了啥，此系统处于完全无法使用状态

### ISSUE THREAD

**Issue by NijiharaTsubasa** [NijiharaTsubasa/BaiduPanAutoReshare#10]
请各位用户等待下次更新，我会尽快

**Comment by mu228** [comment]
啥时候更新呢?你让我好焦灼.- -!

**Comment by NijiharaTsubasa** [comment]
@mu228 问题已查明，但以我的水平难以解决，我去找朋友帮忙，可能得几天

**Comment by mu228** [comment]
好的，更新了以后我过来看看！时刻关注呢！最好能够做好兼容性！因为我发现不是所有空间都支持的，就连我的vPS居然都不能搭建！费解！目前完美实现的只有在电脑用本地PHP模拟器实验成功，无问题！完美！但是在网上诸多问题！看着都头疼！

**Comment by yan1zhao** [comment]
貌似又正常了，请作者看看是不是百度抽风。

**Comment by yan1zhao** [comment]
@NijiharaTsubasa

**Comment by NijiharaTsubasa** [comment]
@mu228 @yan1zhao 已确认是百度在试验新的登录验证机制，现在已经撤下了
请放心我这边也已进行了应对措施，现在他要是真上我能做到第一时间适配

**Comment by yan1zhao** [comment]
好的，希望楼主到时说明一下是更新了什么，因为我已经做了一些修改，到时方便对应。辛苦了！

**Comment by yan1zhao** [comment]
@NijiharaTsubasa  不知道作者您什么时候更新，现在系统无法使用。

**Comment by NijiharaTsubasa** [comment]
这几天实在没时间，对不起大家了，我尽早抽时间更新

**Comment by NijiharaTsubasa** [comment]
@mu228 @yan1zhao 临时解决方案参见 #15
