### ISSUE TITLE
关于4月17号出现的cookie错误反馈

### ISSUE THREAD

**Issue by fantastlcok** [NijiharaTsubasa/BaiduPanAutoReshare#13]
度盘守护是一个非常实用的工具，已经无法离开此工具。

4月17日出现提示Cookie失效，经测试IP未被百度禁封。点击切换用户以及访问转跳页面提示cookie失效，但是可以正常进去文件游览页面。

**Comment by NijiharaTsubasa** [comment]
我这边已经验明了百度网盘新的登录验证机制
但是需要更换登录接口（现在的是贴吧客户端的，需要换成网页端），而我个人水平所限做不出来，当初我就是因为写网页端登录失败了才改用贴吧客户端接口的
现在需要同时满足俩条件 1我喊来写网页版登录的朋友写完 2我有时间 才能更新
我最近忙其他的事忙得喘不过气来所以真不一定什么时候有时间。。。。。。。。

**Comment by NijiharaTsubasa** [comment]
临时解决方案参见 #15

**Comment by NijiharaTsubasa** [comment]
你好，请尝试【最新】的代码，解决了不能登录的问题

**Comment by NijiharaTsubasa** [comment]
提交里想打Close #13 打成 #14 的我
