### ISSUE TITLE
【注意】补档程序无法登录期间cookie失效的临时解决方案

### ISSUE THREAD

**Issue by NijiharaTsubasa** [NijiharaTsubasa/BaiduPanAutoReshare#15]
百度又加回了新的登录机制……登录代码更新了吗？没有@_@

首先用浏览器打开百度网盘主页，登录
然后打开F12，切换到网络选项卡，刷新（登录进入网盘界面后一定要至少刷新一次！！！）
在抓取到的列表里找到home（一般是第一或第二项）点开
复制Request Headers里的Cookie（不含开头的Cookie:）
整个粘贴到mysql的user表对应用户的cookie字段里
cookie里有形如 BDUSS=一串字符; （到分号结尾）的一段内容，把等号后面的部分粘到user表对应用户的BDUSS字段里（鉴于是和cookie里重复的数据，下次更新会删除此字段，但现在暂时需要一并更新）

**Comment by NijiharaTsubasa** [comment]
此方案4月14日即证实有效，没早发出来只是因为我已经忙到没时间来看一眼了。。。。。。。。。。导致不知道百度正式上了新登录机制

**Comment by Sicem98** [comment]
演示：谷歌浏览器
打开http://pan.baidu.com/ 登陆
按下F12，控制台选项卡切换至Network
F5刷新网页，Name列表下找到home（一般都是最上面）点击
在右侧选项卡中选择Headers，往下方拖拽至第二个Request Headers
复制此列表下【Cookie:】里面的内容
粘贴至数据库表user表内对应用户的cookie里面
粘贴内容中有一段为BDUSS=字串; 把其中的字串复制到数据库表user对应用户的bduss里面

**Comment by yan1zhao** [comment]
作者辛苦了，致敬。请问这种添加方式，cookies会失效吗？

**Comment by Sicem98** [comment]
额，咱不是作者啦~我只是替他实验一下。实测cookies没失效，且正常补档。

**Comment by yan1zhao** [comment]
你和作者都很辛苦，都要致敬啊！

**Comment by Sicem98** [comment]
我就是在等作者大大出新版本有个后台登陆，安全点~

**Comment by yan1zhao** [comment]
我朋友做了一个简单的在用，等作者出新版。

**Comment by yan1zhao** [comment]
请问大家有没有出现问题，我按作者最近的cookies修改了sql，正常用了两天后，现在补档程序无法浏览文件列表了。

**Comment by Sicem98** [comment]
我这里还可以。

**Comment by yan1zhao** [comment]
重新再添加了一次用户名密码，可以了。

**Comment by yan1zhao** [comment]
大家有没有问题，我今天晚上发现分享的avi等格式下载不了，是不是百度封了权限？

**Comment by Sicem98** [comment]
我已经很长时间没有使用这个补档程序了，在等新版。也没有尝试

**Comment by mu228** [comment]
最近看到作者貌似更新了。我测试了用临时COOKIE的解决方案。目前问题有后台下载找不到文件。跳转到jump页面的时候提示“由于cookie失效，无法进行补档，请尝试直接访问分享页（提取密码：0）”直接访问分享页是可以的。
这样子的话，应该是不能进行补档的。虽然我没有爆过档！请大家一起讨论一下

**Comment by yan1zhao** [comment]
应该不能自动补档，否则不会称为临时方案。

**Comment by NijiharaTsubasa** [comment]
补档目前是没出问题的，因为我这边的网站（仓库）是正常使用的，要是炸了他们肯定第一时间找上来我。。。

**Comment by LimiQS** [comment]
没问题+1，至少我没收到下面的汇报

**Comment by yan80zhao** [comment]
刚刚发现，程序无法获取到百度云的文件列表了，大家检查一下否也是这样。

**Comment by NijiharaTsubasa** [comment]
借地（在这回复的话应该楼上所有人都能收到通知）
我更新了个“获取不限速下载地址”，虽然貌似有IP限制，但是都在国内的话没问题

**Comment by yan1zhao** [comment]
楼主所说的不限速下载地址是什么意思，直接点击下载文件（非文件夹）？

**Comment by Sicem98** [comment]
倒是希望能加个后台登陆的说-0-，表示http验证完全懵逼

**Comment by yan80zhao** [comment]
请问作者老兄，cookie是定期失效吗，昨天按方法修改user表，正常了，今天补档程序又提示失效了。

**Comment by Sicem98** [comment]
一般情况下基本能用很长时间，就像贴吧云签一样自动很久

**Comment by yan80zhao** [comment]
我第一次管了很久，现在一天不到就提示失效。

**Comment by NijiharaTsubasa** [comment]
请各位尝试【最新】的代码，解决了不能登录的问题
这里回复过的人比较多，为了通知到在这里说一下

**Comment by NijiharaTsubasa** [comment]
修复无法登录后，jump.php反而报cookies失效无法补档
请各位放心我会在24小时内修复

**Comment by yan80zhao** [comment]
作者辛苦了，致敬！

**Comment by fantastlcok** [comment]
好像数据库里没有BDUSS字段

**Comment by NijiharaTsubasa** [comment]
@fantastlcok 这个字段应该是删了的，我周末会检查有没有残留，但我有可能忘，如果我忘了回复提醒我一下
