### ISSUE TITLE
当账户没有设置用户名时，添加补档记录会显示无此用户

### ISSUE THREAD

**Issue by 872517414** [NijiharaTsubasa/BaiduPanAutoReshare#16]
RT 当没有设置用户名将会导致此状况。
错误：用户【XXXX】未添加进数据库！

**Comment by 872517414** [comment]
为何我设置了用户名也还是不能用= =

**Comment by 872517414** [comment]
原来在浏览文件里添加就可以= = 我白白填写了用户名orz 幸好也是专用号，不过强迫症= =

**Comment by NijiharaTsubasa** [comment]
你好，添加链接的时候是先模拟提取，然后根据取到的用户名去数据库里查用户的，没有用户名的用户百度会再邮箱地址中间加...，自然就取不到了，建议您设置一个用户名，然后删掉这个用户重新添加，带来不便实在抱歉
