### ISSUE TITLE
当同一文件夹内有相同字符的两个文件，且一个保护了一个没保护会出现BUG

### ISSUE THREAD

**Issue by 872517414** [NijiharaTsubasa/BaiduPanAutoReshare#17]
![qq 20160508194215](https://cloud.githubusercontent.com/assets/9050713/15097662/22bbfc3c-1555-11e6-90ce-cf57e947bc83.png)
如图

**Comment by daojichang** [comment]
你好！我按照作者说的替换了bduss.但是还是显示cookie失效！想来请教一下！已加企鹅号！

**Comment by daojichang** [comment]
我已经按照作者说的替换了bduss！但是还是提示cookie失效！想请教一下！已加企鹅号！

**Comment by 872517414** [comment]
单单替换bduss没用 还要替换cookie
