### ISSUE TITLE
对了，顺便扔两个有意思的度盘玩意上来

### ISSUE THREAD

**Issue by 872517414** [NijiharaTsubasa/BaiduPanAutoReshare#19]
https://github.com/oott123/bpcs_uploader
http://developer.baidu.com/wiki/index.php?title=docs/pcs/rest/overview

**Comment by chenxuuu** [comment]
pcs权限早就不能用了吧。。。

**Comment by NijiharaTsubasa** [comment]
开放API连分享都没，没什么用。。。。。。
