### ISSUE TITLE
bd-admin/browse.php代码错误

### ISSUE THREAD

**Issue by LimiQS** [NijiharaTsubasa/BaiduPanAutoReshare#2]
bd-admin/browse.php (line 80):

    <a href="tools/dl.php?<?=rawurlencode($v['name'])?>" target="_blank">自定义分享</a>

应该为：

    <a href="tools/share.php?<?=$v['fid']?>" target="_blank">自定义分享</a>

对于文件夹（if($v['isdir'])）错误地调用dl.php结果是一定会返回错误“找不到文件”，而且用户界面描述和源代码功能大幅度不相符，疑是编写错误

**Comment by NijiharaTsubasa** [comment]
收到
