### ISSUE TITLE
可以考虑利用一下联通的缓存服务器

### ISSUE THREAD

**Issue by chenxuuu** [NijiharaTsubasa/BaiduPanAutoReshare#24]
例如：
http://7xt3k7.com2.z0.glb.clouddn.com/bdlogo.svg
可以转换为：
http://120.52.72.21/7xt3k7.com2.z0.glb.clouddn.com/bdlogo.svg
http://221.176.14.72/7xt3k7.com2.z0.glb.clouddn.com/bdlogo.svg

ip列表：http://proxydb.net/list?protocol=http&minavail=0&maxtime=0&limit=25&ip_filter=&port_filter=&host_filter=&country_filter=&isp_filter=Unicom&via_filter=

可以绕过ip地区限制？（貌似

**Comment by NijiharaTsubasa** [comment]
它缓存服务器里没有的文件能抓取吗？

**Comment by chenxuuu** [comment]
没文件好像是自动抓取然后缓存的，能保存好几天

**Comment by NijiharaTsubasa** [comment]
现在已经确认那个有IP地区限制的接口也被限速了
我现在直接用百度的其他API获取高速地址了
我觉得联通缓存这种东西不要依靠为好
