### ISSUE TITLE
突来的翻车 错误：找不到编号为XX的记录

### ISSUE THREAD

**Issue by fantastlcok** [NijiharaTsubasa/BaiduPanAutoReshare#28]
错误：找不到编号为XX的记录

所有链接全部翻车...也没改啥代码，突然就翻车了。这是咋了。

**Comment by NijiharaTsubasa** [comment]
抱歉回复的有点晚，请问你是升级代码之后出现的这个问题还是莫名其妙突然出现的
说实话这东西我承认我并没有在认真维护，如果更新出了什么岔子一点都不奇怪。。。

**Comment by fantastlcok** [comment]
@NijiharaTsubasa 恩，突然出现了。几天后又恢复正常了...无法理解。
