### ISSUE TITLE
下载地址太慢了，是否有更快的下载地址

### ISSUE THREAD

**Issue by raycraft** [NijiharaTsubasa/BaiduPanAutoReshare#29]
下载地址太慢了，无论是高速的还是限速的。是否有更快的下载地址

**Comment by NijiharaTsubasa** [comment]
还有个接口可以获取到下载地址，我找时间试试那个，但是那个只能取出来一个地址

**Comment by raycraft** [comment]
太好了，有了高速下载地址，BaiduPanAutoReshare才会如虎添翼，发挥出应有的效果，再次感谢up主！

**Comment by NijiharaTsubasa** [comment]
不过我不保证那个接口取出来的地址能正常用（比如有没有IP限制一类的）
我现在没有时间（上班了），加上我不会做界面，要不然我就直接写一个走高速地址的百度网盘下载器了，现在的干净云还是不够干净（P2P没去掉）

**Comment by raycraft** [comment]
有了下载地址，我就可以直接播放了，不需要什么界面

**Comment by NijiharaTsubasa** [comment]
现在百度是这样的
云管家请求获取单个下载地址的接口，服务器根据附带的参数（有没有sup=1）生成一个不限速或限速的地址，然后返回一个302跳转
所以我说只能取到一个地址

我现在用的是百度废弃的取批量下载地址的接口，上面那个有IP限制的是新版接口，下面没有IP限制的是旧版接口，旧版的被限速了，现在看来新版的好像也被限速了（毕竟是废弃的）

**Comment by raycraft** [comment]
可否参考下这个项目https://github.com/acgotaku/BaiduExporter
换个UA 及其他referer等获取高速下载地址呢？

**Comment by NijiharaTsubasa** [comment]
你好，最新版本已增加云管家获取高速下载地址接口，拖了这么久不好意思，这个原理我是早就知道的，今天做了一些额外研究确保可靠性才加入。
原理很简单，有兴趣的可以去看一下代码
