### ISSUE TITLE
感谢作者！

### ISSUE THREAD

**Issue by yan80zhao** [NijiharaTsubasa/BaiduPanAutoReshare#3]
不知道绅士仓库是不是您的网站，已捐赠200元，希望程序能及时更新，感谢！

**Comment by jimmyd95** [comment]
雖然我很想說這是我的網站＝。＝但是我真的不知道那個網站是誰的⋯⋯
不過你既然是github的人的話，我就加你一下了。我不是搞網站的，是弄軟件那一方面的：）而且我才剛剛開始弄github，基本上什麼都不會。能被你找到也算是緣分吧，有機會聊聊。
ps. 話說紳士倉庫⋯⋯⋯⋯是我想的東西麼＝。＝｜｜你⋯⋯我就不好奇了，不過我蠻好奇你說的程序更新是哪裏更新？？

**Comment by yan80zhao** [comment]
sorry！我也看不懂那个网站，可能是日漫为主的吧，年轻人才懂，我老了。。。
感谢您的辛勤劳动，我说的更新是指百度云存储的策略会经常变化，您的程序如果能及时跟进是我们的福气，当然这确实会比较辛苦，再次感谢！

**Comment by jimmyd95** [comment]
=.=我用很懷疑的眼神看著你⋯⋯⋯⋯
嘛，反正應該都是看看無聊用的，會有人喜歡，也會有人去做這種網站：）這樣程序員們才能賺更多錢嘛～～
呃呃⋯⋯說實話我不確定你說的那個程序跟進是什麼意思，你能更詳細的解釋一下麼？（或者你真的發錯人了⋯⋯⋯⋯）
如果有需要，我會馬上更新程序，不過我真的不記得在百度雲那個方面寫過程序啊⋯⋯⋯⋯

**Comment by NijiharaTsubasa** [comment]
绅士仓库并不是我的网站，这个程序原本是14年初我给他们开发来内部使用的，运行了一年半没出什么问题，经过站长同意后我就开源了
关于维护的事请各位放心，因为我们自己也在用，所以会很快适配百度云的变化

而且我们用的大部分接口都是百度云管家的（小部分是网页版的接口，只有极少数需要分析网页内容，上次百度盘升级就是这里出了差），百度不会轻易更改的，他们也需要向前兼容，所以这个尽管放心

**Comment by NijiharaTsubasa** [comment]
2楼那位是点了Watch然后收到通知了吧，Watch之后有人给项目发issue都会收到通知的，并不是说你

**Comment by yan80zhao** [comment]
感谢作者，您辛苦了，加油！

**Comment by jimmyd95** [comment]
我都不記得我點擊了watch⋯⋯⋯⋯不過多少明白了，謝謝了。

**Comment by yan80zhao** [comment]
大家都是朋友，祝大家好运！
