### ISSUE TITLE
添加用户不成功

### ISSUE THREAD

**Issue by gogo81745** [NijiharaTsubasa/BaiduPanAutoReshare#4]
安装完毕后，添加用户那步操作失败
根据[这里](http://www.ssgo.org/threads/%E6%88%91%E6%B5%8B%E8%AF%95%E4%BA%86%E4%B8%80%E4%B8%8B%E3%80%90%E5%BA%A6%E5%A8%98%E7%9B%98%E5%88%86%E4%BA%AB%E5%AE%88%E6%8A%A4%E7%A8%8B%E5%BA%8F%E3%80%91.1473/)的截图，添加用户完毕后会有个alert("用户【...】添加成功!")的提示，但是我实际操作中没有出现这个，什么提示都没有。
于是来问下可能造成这种情况的原因及解决方案

**Comment by NijiharaTsubasa** [comment]
麻烦您看一下PHP的错误日志，告诉我出了什么错

**Comment by NijiharaTsubasa** [comment]
另外你给的那个链接如果你能回帖的话，麻烦告诉楼主一声，开发者已经看见了他遇见的问题，会采取一些改进措施
更详细的说明我也会写的，只是最近比较忙可能不能及时写出来

**Comment by yan80zhao** [comment]
没看懂上面的回贴，“另外你给的那个链接如果你能回帖的话，麻烦告诉楼主一声”，你和楼主分别指的是谁，呵呵。
我在使用php5.3时有问题，也按readme进行了相应的设置，但没有成功，不过没有记详细的参数，所以提醒了楼主一下，因为我当时是改用php5.4成功使用本程序的。再次感谢开发者！

**Comment by NijiharaTsubasa** [comment]
设置方面我也不是特别清楚，仓库最开始用的就是PHP5.3，我只是把我当时改完能用了的设置写了进去，不知道还有什么别的会影响使用，如果能提供错误信息那再好不过了
另外当年我语文长期落后班里平均分10分的，不要在意（

**Comment by yan80zhao** [comment]
程序虽有些不完善的地方，但能够使用已经是非常感谢了，我也已经把两个网站合并成了一个，还费解为什么要弄成两个网站：）楼主可以提供一下你的php错误信息，方便作者进行判断。

**Comment by gogo81745** [comment]
@NijiharaTsubasa 
php错误日志

> [Fri Feb 05 02:06:40.895317 2016] [:error] [pid 5719] [client 123.158.147.85:3329] PHP Fatal error:  Call to undefined function curl_init() in /var/www/html/baidu/bd-admin/common.php on line 24, referer: https://gogo.moe/baidu/bd-admin/switch_user.php?add_user=1

使用的是PHP 5.5.9，Apache 2.4.7
帖子也帮忙回了

**Comment by SuperHentai** [comment]
这个问题应该是没有装curl扩展

**Comment by gogo81745** [comment]
确实是没有装curl扩展的原因，装了以后可以正常使用了
在自己电脑上实验都没啥问题，功能稍微看看也都用的来，无语的是在vps上用就提示"cookie失效，或者百度封了ip"(估计是百度封了ip) (~￣△￣)~
最后感谢下作者，以及楼上提供解决方案的朋友

**Comment by NijiharaTsubasa** [comment]
@gogo81745 应该不是百度封了IP，我只遇到过一次流量太太太太太太太太太太大了IP被封的情况，我也不好说原因是啥，这东西的错误处理太渣了，一是当时我PHP水平本来就很渣，二是因为最开始是内部使用，能用就行了，没考虑那么多（

@yan80zhao 弄成两个是因为。。。还是因为一开始是内部使用的，当时我只写了个补档，后台是用别的语言写的，后来才做网页版后台，我想反正内部使用，我不做登录了，我直接加个HTTP登录，于是就做成了单独的网站……………………………………然后就这么保留到了现在，囧，我现在有合成一个的计划

**Comment by woi911** [comment]
@NijiharaTsubasa 作为二次元同好，先感谢您开发分享的程序呢！

因为知道是度娘盘分享守护程序是调用了百度的API，很多问题并不是作者您造成的，也不是您想明文。所以当时也没有想把百度锅丢给作者您，呵呵。

28000张无损，28000个链接，出于安全考虑，所以没用使用守护程序，也就没有通知请求作者您改进。


**祝各位新年快乐，大吉大利！**
