### ISSUE TITLE
链接度盘出现cookie错误

### ISSUE THREAD

**Issue by fantastlcok** [NijiharaTsubasa/BaiduPanAutoReshare#8]
最近出现的，还有修复的可能么？

**Comment by NijiharaTsubasa** [comment]
你好，请升级到昨天的最新版本（此版本解决了添加链接失效），然后在添加用户界面重新登录一遍失效的用户就可以了
cookie失效只要重新登录一遍这个用户来重新获取cookie就行了（注意不要先删除，直接点登录）

**Comment by NijiharaTsubasa** [comment]
很抱歉回复的有些晚，我平时用的是bitbucket，很少上github看通知

**Comment by NijiharaTsubasa** [comment]
您好，目前由于百度升级登录机制，此系统暂时处于无法使用状态，在我更新（估计要一段时间= =）前的临时解决方案参见 #15

**Comment by NijiharaTsubasa** [comment]
你好，请尝试【最新】的代码，解决了不能登录的问题
