### ISSUE TITLE
数据库上传总是有问题

### ISSUE THREAD

**Issue by mu228** [NijiharaTsubasa/BaiduPanAutoReshare#9]
我找了N个支持MySQL的空间,没有一个成功的.
错误
SQL 查询:

CREATE TABLE IF NOT EXISTS  `log_new` (

 `ID` INT( 11 ) NOT NULL PRIMARY KEY AUTO_INCREMENT ,
 `IP` VARCHAR( 15 ) NOT NULL ,
 `level` TINYINT( 4 ) NOT NULL ,
 `content` TEXT NOT NULL
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4;

MySQL 返回： 文档

#1115 - Unknown character set: 'utf8mb4' 

大多数出现这样的代码.
请问是为什么呢!和phpmyadmin版本没有关系吧。

**Comment by NijiharaTsubasa** [comment]
可能是MySQL版本的问题，这个下次更新我会修复
注意：4月14日起，因为百度不知道改了啥，此系统目前完全无法使用，请等待下次更新（我比较忙，只能抽空修复）

**Comment by NijiharaTsubasa** [comment]
手动修复方法：将utf8mb4改为utf8

**Comment by mu228** [comment]
果然是utf8的问题,我已经试过修改了.能导入成功.不错!可以导入.

**Comment by NijiharaTsubasa** [comment]
这个我设置的应该是utf8的，可能我建表时手滑选错了，下次更新我会改掉sql文件的内容
